// Shared animated-gradient keyframes, reused by the title and buttons.
const gradientKeyframes = {
  "@keyframes gradient": {
    "0%": { backgroundPosition: "0% 50%" },
    "50%": { backgroundPosition: "100% 50%" },
    "100%": { backgroundPosition: "0% 50%" },
  },
};

export const styles = {
  mainContainer: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    bgcolor: "white",
    position: "relative",
    overflow: "hidden",
  },
  splashScreen: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    bgcolor: "white",
    zIndex: 9999,
  },
  gradientBackground: {
    position: "absolute",
    top: { xs: "-20%", sm: "-30%" },
    left: "50%",
    transform: "translateX(-50%)",
    width: { xs: "150%", sm: "120%", md: "100%" },
    height: { xs: "60%", sm: "70%", md: "80%" },
    background:
      "radial-gradient(circle, rgba(46, 108, 232, 0.4) 0%, rgba(90, 141, 245, 0.3) 40%, transparent 70%)",
    borderRadius: "50%",
    filter: "blur(60px)",
    zIndex: 0,
    animation: "floatGradient 20s ease-in-out infinite",
    "@keyframes floatGradient": {
      "0%": {
        top: { xs: "-20%", sm: "-30%" },
        left: "50%",
        opacity: 0.8,
      },
      "20%": {
        top: { xs: "-10%", sm: "-20%" },
        left: "40%",
        opacity: 1,
      },
      "40%": {
        top: { xs: "-30%", sm: "-40%" },
        left: "60%",
        opacity: 0.9,
      },
      "60%": {
        top: { xs: "-5%", sm: "-15%" },
        left: "55%",
        opacity: 1,
      },
      "80%": {
        top: { xs: "-25%", sm: "-35%" },
        left: "45%",
        opacity: 0.85,
      },
      "100%": {
        top: { xs: "-20%", sm: "-30%" },
        left: "50%",
        opacity: 0.8,
      },
    },
  },
  carouselContainer: {
    width: "100%",
    mb: { xs: 6, sm: 8 },
    position: "relative",
    zIndex: 1,
  },
  contentContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    position: "relative",
    zIndex: 1,
    minHeight: { xs: "60vh", sm: "70vh", md: "80vh" },
    py: { xs: 8, sm: 10, md: 12 },
  },
  title: {
    fontSize: { xs: "1.75rem", sm: "2.25rem", md: "3rem" },
    fontWeight: 700,
    background: "linear-gradient(45deg, #2e6ce8, #5a8df5, #2e6ce8)",
    backgroundSize: "200% 200%",
    backgroundClip: "text",
    WebkitBackgroundClip: "text",
    color: "transparent",
    animation: "gradient 3s ease infinite",
    mb: { xs: 2, sm: 3 },
    mt: 4,
    lineHeight: 1.2,
    ...gradientKeyframes,
  },
  subtitle: {
    fontSize: { xs: "0.95rem", sm: "1.05rem", md: "1.15rem" },
    color: "#4a4a4a",
    mb: { xs: 4, sm: 5 },
    px: { xs: 1, sm: 2 },
    lineHeight: 1.6,
  },
  cardsContainer: {
    width: "100%",
    maxWidth: "1600px",
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    gap: { xs: 4, md: 3 },
    mb: { xs: 6, sm: 8 },
  },
  worshipCard: {
    bgcolor: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: 3,
    border: "1px solid rgba(255, 255, 255, 0.3)",
    boxShadow: "0 4px 16px 0 rgba(46, 108, 232, 0.1)",
    flex: 1,
    width: "100%",
  },
  worshipContent: {
    p: { xs: 3, sm: 4 },
    display: "flex",
    flexDirection: "row",
    gap: { xs: 3, sm: 5 },
    alignItems: "center",
  },
  zoomLogoContainer: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: { xs: "80px", sm: "120px" },
    height: { xs: "80px", sm: "120px" },
  },
  worshipTextContent: {
    flex: 1,
    textAlign: "left",
  },
  zoomIcon: {
    fontSize: { xs: "3rem", sm: "3.5rem" },
    color: "#2e6ce8",
    mb: 2,
    display: "block",
  },
  worshipTitle: {
    fontSize: { xs: "1rem", sm: "1.1rem" },
    fontWeight: 600,
    color: "#1a1a1a",
    mb: 3,
  },
  scheduleBox: {
    mb: 2,
  },
  scheduleItem: {
    fontSize: { xs: "0.9rem", sm: "1rem" },
    color: "#1a1a1a",
    mb: 0.5,
  },
  scheduleTime: {
    fontSize: { xs: "0.85rem", sm: "0.95rem" },
    color: "#4a4a4a",
  },
  zoomInfoBox: {
    mt: 3,
    pt: 2,
    borderTop: "1px solid rgba(46, 108, 232, 0.2)",
    display: "flex",
    flexDirection: { xs: "column", sm: "row" },
    alignItems: { xs: "stretch", sm: "center" },
    justifyContent: "space-between",
    gap: 2,
  },
  zoomInfoText: {
    display: "flex",
    flexDirection: "column",
    gap: 0.5,
  },
  zoomInfo: {
    fontSize: { xs: "0.85rem", sm: "0.9rem" },
    color: "#2e6ce8",
    mb: 0.5,
  },
  zoomButton: {
    background: "linear-gradient(45deg, #2e6ce8, #5a8df5, #2e6ce8)",
    backgroundSize: "200% 200%",
    animation: "gradient 3s ease infinite",
    color: "white",
    py: 1,
    px: 3,
    fontSize: { xs: "0.8rem", sm: "0.85rem" },
    boxShadow: "0 4px 14px 0 rgba(46, 108, 232, 0.4)",
    textTransform: "none",
    whiteSpace: "nowrap",
    ...gradientKeyframes,
    "&:hover": {
      background: "linear-gradient(45deg, #2558c0, #4a7de6, #2558c0)",
      backgroundSize: "200% 200%",
      boxShadow: "0 6px 20px 0 rgba(46, 108, 232, 0.5)",
    },
  },
  cardsGrid: {
    width: "100%",
    mb: { xs: 6, sm: 8 },
  },
  glassCard: {
    bgcolor: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: 2,
    border: "1px solid rgba(255, 255, 255, 0.3)",
    boxShadow: "0 4px 16px 0 rgba(46, 108, 232, 0.1)",
    height: "100%",
    transition: "all 0.3s ease",
    "&:hover": {
      boxShadow: "0 6px 20px 0 rgba(46, 108, 232, 0.2)",
      transform: "translateY(-4px)",
    },
  },
  cardContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    py: 3,
  },
  cardIcon: {
    fontSize: { xs: "2rem", sm: "2.5rem" },
    color: "#2e6ce8",
    mb: 1,
  },
  cardTitle: {
    fontSize: { xs: "0.9rem", sm: "1rem" },
    fontWeight: 600,
    color: "#1a1a1a",
    mb: 0.5,
  },
  cardText: {
    fontSize: { xs: "0.75rem", sm: "0.85rem" },
    color: "#4a4a4a",
  },
  cardButton: {
    fontSize: { xs: "0.9rem", sm: "1rem" },
    fontWeight: 600,
    color: "#2e6ce8",
    textTransform: "none",
    "&:hover": {
      bgcolor: "rgba(46, 108, 232, 0.1)",
    },
  },
  followButton: {
    background: "linear-gradient(45deg, #2e6ce8, #5a8df5, #2e6ce8)",
    backgroundSize: "200% 200%",
    animation: "gradient 3s ease infinite",
    color: "white",
    py: { xs: 1.5, sm: 1.25 },
    px: { xs: 3, sm: 4 },
    fontSize: { xs: "0.9rem", sm: "0.875rem" },
    boxShadow: "0 4px 14px 0 rgba(46, 108, 232, 0.4)",
    mt: 2,
    textTransform: "none",
    width: { xs: "100%", sm: "auto" },
    ...gradientKeyframes,
    "&:hover": {
      background: "linear-gradient(45deg, #2558c0, #4a7de6, #2558c0)",
      backgroundSize: "200% 200%",
      boxShadow: "0 6px 20px 0 rgba(46, 108, 232, 0.5)",
    },
  },
  instagramCard: {
    bgcolor: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(10px)",
    borderRadius: 3,
    border: "1px solid rgba(255, 255, 255, 0.3)",
    boxShadow: "0 4px 16px 0 rgba(46, 108, 232, 0.1)",
    flex: 1,
    width: "100%",
    display: "flex",
    flexDirection: "column",
  },
  instagramCardContent: {
    p: { xs: 3, sm: 4 },
    display: "flex",
    flexDirection: "row",
    gap: { xs: 3, sm: 5 },
    alignItems: "center",
    flex: 1,
  },
  instagramProfilePicture: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: { xs: "80px", sm: "120px" },
    height: { xs: "80px", sm: "120px" },
    borderRadius: "50%",
    overflow: "hidden",
    border: "4px solid transparent",
    backgroundImage:
      "linear-gradient(white, white), linear-gradient(45deg, #f09433 0%, #e6683c 25%, #dc2743 50%, #cc2366 75%, #bc1888 100%)",
    backgroundOrigin: "border-box",
    backgroundClip: "padding-box, border-box",
    boxShadow: "0 4px 12px 0 rgba(188, 24, 136, 0.3)",
  },
  instagramTextContent: {
    flex: 1,
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  instagramTitle: {
    fontSize: { xs: "0.9rem", sm: "1rem" },
    fontWeight: 700,
    color: "#1a1a1a",
    mb: { xs: 0.5, sm: 1 },
  },
  instagramSubtext: {
    fontSize: { xs: "0.85rem", sm: "0.95rem" },
    color: "#4a4a4a",
    mb: { xs: 0, sm: 1.5 },
    lineHeight: 1.5,
  },
  buttonStack: {
    justifyContent: "center",
    flexWrap: "wrap",
  },
  containedButton: {
    bgcolor: "#2e6ce8",
    color: "white",
    py: { xs: 1.5, sm: 1.25 },
    fontSize: { xs: "0.9rem", sm: "0.875rem" },
    boxShadow: "0 4px 14px 0 rgba(46, 108, 232, 0.4)",
    "&:hover": {
      bgcolor: "#2558c0",
      boxShadow: "0 6px 20px 0 rgba(46, 108, 232, 0.5)",
    },
  },
  outlinedButton: {
    borderColor: "#2e6ce8",
    color: "#2e6ce8",
    py: { xs: 1.5, sm: 1.25 },
    fontSize: { xs: "0.9rem", sm: "0.875rem" },
    borderWidth: 2,
    "&:hover": {
      borderColor: "#2558c0",
      borderWidth: 2,
      bgcolor: "rgba(46, 108, 232, 0.05)",
    },
  },
  mapSection: {
    width: "100%",
    mb: { xs: 6, sm: 8 },
  },
  mapTitleContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    mb: 3,
  },
  mapIcon: {
    fontSize: { xs: "1.75rem", sm: "2rem", md: "2.25rem" },
    color: "#2e6ce8",
  },
  mapTitle: {
    fontSize: { xs: "1.5rem", sm: "1.75rem", md: "2rem" },
    fontWeight: 700,
    color: "#1a1a1a",
    textAlign: "center",
  },
  mapContainer: {
    width: "100%",
    maxWidth: "800px",
    margin: "0 auto",
    borderRadius: 3,
    overflow: "hidden",
    boxShadow: "0 4px 16px 0 rgba(46, 108, 232, 0.1)",
  },
};
